[tool.poetry]
name = "lucy"
version = "4.8.7"
description = ""
authors = ["Brandon Graham Cobb <brandongrahamcobb@icloud.com>"]
repository = "https://github.com/brandongrahamcobb/lucy.git"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12.8"


[build-system]
requires = ["poetry-core", "setuptools"]
build-backend = "poetry.core.masonry.api"
